import os
import sys
import json
import httpx
from datetime import datetime

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CHAT_DATA_DIR = os.path.join(BASE_DIR, "chat_data")
os.makedirs(CHAT_DATA_DIR, exist_ok=True)

OLLAMA_MM = "gemma3:12b"
OLLAMA_SM = "gemma3:4b"

OLLAMA_API_URL = "http://127.0.0.1:11434/api/chat"

SM_INSTRUCTION_PROMPT = """
    You are a smaller LLM.
    Your task is to generate a response for the given part of the code, based on the instructions provided.
    In your response, do not include any explanations or reasoning, just provide the answer for the given part as a single JSON string, without any additional text.
    The instructions are: """

SM_RECOMBINE_PROMPT = """
    You are the control LLM.
    Your task is to take the 3 smaller parts generated by the smaller LLMs and reassemble them into a single, coherent response to the original user message.
    Return your answer as normal text and not a JSON string.
    Do not include any statements relating to the fact that you are recombining parts, just provide the final answer as if you were responding to the original user message.
    The 3 parts are: """

def load_all_chats():
    chats = []
    for filename in os.listdir(CHAT_DATA_DIR):
        if filename.endswith(".json"):
            filepath = os.path.join(CHAT_DATA_DIR, filename)
            with open(filepath, "r") as f:
                try:
                    data = json.load(f)
                    chats.append({
                        "id": data.get("id", filename.replace(".json", "")),
                        "title": data.get("title", "New Chat"),
                        "updated_at": data.get("updated_at", "")
                    })
                except json.JSONDecodeError:
                    pass
    chats.sort(key=lambda x: x.get("updated_at", ""), reverse=True)
    return chats

def get_chat(chat_id: str):
    filepath = os.path.join(CHAT_DATA_DIR, f"{chat_id}.json")
    if os.path.exists(filepath):
        with open(filepath, "r") as f:
            try:
                return json.load(f)
            except json.JSONDecodeError:
                return None
    return None

def save_chat(chat_id: str, data: dict):
    filepath = os.path.join(CHAT_DATA_DIR, f"{chat_id}.json")
    
    if not data.get("title") and data.get("messages"):
        first_user_msg = next((m["content"] for m in data["messages"] if m["role"] == "user"), "New Chat")
        data["title"] = first_user_msg[:30] + ("..." if len(first_user_msg) > 30 else "")
        
    data["updated_at"] = datetime.now().isoformat()
    
    with open(filepath, "w") as f:
        json.dump(data, f, indent=2)

async def generate_ai_response(messages: list):

    payload = {
        "model": OLLAMA_MM,
        "messages": messages,
        "stream": False
    }
    
    eval_count = 0
    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(OLLAMA_API_URL, json=payload, timeout=300.0)
            response.raise_for_status()
            result = response.json()
            ai_content = result.get("message", {}).get("content", "Error generating response.")
            eval_count = result.get("eval_count", 0)
    except Exception as e:
        ai_content = f"Sorry, could not connect to Ollama: {str(e)}"

    tasks = [task for task in ai_content.split("\n") if task]
    SM_responses = []

    for task in tasks:
        sm_payload = {
            "model": OLLAMA_SM,
            "messages": [{"role": "system", "content": str(SM_INSTRUCTION_PROMPT + task)}],
            "stream": False
        }
        try:
            async with httpx.AsyncClient() as client:
                response = await client.post(OLLAMA_API_URL, json=sm_payload, timeout=300.0)
                response.raise_for_status()
                result = response.json()
                sm_response = result.get("message", {}).get("content", "")
                SM_responses.append(sm_response)
        except Exception as e:
            SM_responses.append(f"Error processing task: {str(e)}")

    payload = {
        "model": OLLAMA_SM,
        "messages": [{"role": "system", "content": str(SM_RECOMBINE_PROMPT.join(SM_responses))}],
        "stream": False
    }

    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(OLLAMA_API_URL, json=payload, timeout=300.0)
            response.raise_for_status()
            result = response.json()
            ai_content = result.get("message", {}).get("content", "Error generating response.")
            eval_count = result.get("eval_count", 0)
    except Exception as e:
        ai_content = f"Sorry, could not connect to Ollama: {str(e)}"

    return ai_content, eval_count

def get_stats():
    total_messages = 0
    total_tokens = 0
    chat_count = 0
    saved_energy = 0.0
    energy_saved_per_token = 1.937
    
    for filename in os.listdir(CHAT_DATA_DIR):
        if filename.endswith(".json"):
            chat_count += 1
            filepath = os.path.join(CHAT_DATA_DIR, filename)
            with open(filepath, "r") as f:
                try:
                    data = json.load(f)
                    total_messages += len(data.get("messages", []))
                    chat_tokens = data.get("tokens_used", 0)
                    total_tokens += chat_tokens
                    saved_energy += chat_tokens * energy_saved_per_token
                except json.JSONDecodeError:
                    pass
                    
    return {
        "chat_count": chat_count,
        "total_messages": total_messages,
        "total_tokens": total_tokens,
        "saved_energy": saved_energy,
    }

def verif_models(large: str, small: str):
    file = "./setup/models.txt"
    valid_models = set()

    if os.path.exists(file):
        with open(file, "r") as f:
            for line in f:
                clean = line.strip()
                if not clean.startswith('#'):
                    valid_models.add(clean)
    
    return_bool = large in valid_models and small in valid_models
    if not return_bool:
        print(f"Incorrect usage. {large} and {small} are inexistent models or have not been added to ./setup/models.txt")
        exit(1)

    return return_bool

def set_models(*args):
    if verif_models(args[2], args[3]):
        OLLAMA_MM = args[2]
        OLLAMA_SM = args[3]